version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=restaurantDB  # Optional, specifying the database
    command: ["mongod", "--noauth"]  # Disable authentication

  restaurant-service:
    build:
      context: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGO_URI=mongodb://admin:password@mongo-db:27017/restaurantDB
    depends_on:
      - mongo

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - MONGO_URI=mongodb://admin:password@mongo-db:27017/orderDB
    depends_on:
      - mongo

  delivery-service:
    build:
      context: ./delivery-service
    container_name: delivery-service
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - MONGO_URI=mongodb://admin:password@mongo-db:27017/deliveryDB
    depends_on:
      - mongo

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - MONGO_URI=mongodb://admin:password@mongo-db:27017/userDB
    depends_on:
      - mongo

volumes:
  mongo-data:
